### ISSUE TITLE
Exception when setting-up the station

### ISSUE THREAD

**Issue by lucky62** [kerikun11/IR-station#6]
Hello.
I have a NodeMCU module (LoLin) and I am trying to run the IR-station with it.
Firmware and filesystem was loaded ok.

I can connect to the "IR-Station" wifi and I can see the setup page in the browser.
But when I push the "Set as Station" button then I get the exception.
Below is the captured serial output.
Please help.
Thanks.

SERIAL OUTPUT:
=================
New Request
URI: /mode/station
Method: GET
Arguments count: 4
	1073695364 = 1073695388
	1073695364 = 1073695388
	1073695364 = 1073695388
	1073695364 = 1073695388
Hostname: ir
SSID: myssid
Password: mypwd
Stealth: false

Exception (0):
epc1=0x402072f0 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff1c60 end: 3fff2210 offset: 01a0

stack
3fff1e00:  40106e58 3fff5d0c 3fff33f7 00000030  
3fff1e10:  ffffffff 00000020 3ffee430 000005e4  
3fff1e20:  00000001 40104183 3ffee460 00000022  
3fff1e30:  3fffc200 40106e20 3fffc258 4000050c  
3fff1e40:  400043e6 00000030 00000016 ffffffff  
3fff1e50:  400044ab 3fffc718 3fff1f40 08000000  
3fff1e60:  60000200 08000000 00000000 00000000  
3fff1e70:  0000ffff 00000000 ffffff00 003fe000  
3fff1e80:  40244c80 00000484 003fe000 00000030  
3fff1e90:  4022e839 000003fe 00001000 00000609  
3fff1ea0:  00000484 60000200 3fff5694 00000000  
3fff1eb0:  00000008 00000000 ffffff00 3fff5694  
3fff1ec0:  000003ff 000003fd 3fff2040 00000030  
3fff1ed0:  3fffc278 40102d2c 3fffc200 00000022  
3fff1ee0:  3ffeab60 00000005 00000000 40106ea6  
3fff1ef0:  4022ed56 00000030 00000016 ffffffff  
3fff1f00:  4022ece9 ffffff42 3fff2040 00000020  
3fff1f10:  00000000 3fff3d00 00000002 000000fb  
3fff1f20:  0000003d 00000001 3ffefb00 00000001  
3fff1f30:  3fff5694 00000001 3fff2040 00000030  
3fff1f40:  00000002 4000410f 00000020 3fff2040  
3fff1f50:  3fffc718 40004a3c 000003fe 40244c80  
3fff1f60:  3fffc718 40105c72 000003fe 4010717c  
3fff1f70:  40004b31 000003fe 4022e768 4022e751  
3fff1f80:  3fff5d0c 4022e839 3fff5694 000003ff  
3fff1f90:  000003fd 3fff2040 3fff5694 000003fd  
3fff1fa0:  ffffff01 55aa55aa 00000007 0000001c  
3fff1fb0:  0000001c 000000a5 000000a7 000003ff  
3fff1fc0:  4022ec28 3fff5694 3fff5694 00000001  
3fff1fd0:  00000001 3fff2060 4022ed8d 3ffef760  
3fff1fe0:  3fff5694 00000001 3fff2040 00000000  
3fff1ff0:  3fff5754 3fff20a1 00000001 4022ee3c  
3fff2000:  3fff2040 3fff5694 3ffe850f 3ffe84f9  
3fff2010:  3fff2060 3fff5694 3fff5694 3ffe850f  
3fff2020:  4022ee78 3fff4f24 00000000 4020122b  
3fff2030:  4020cd80 00000072 3fff46e4 4020d64e  
3fff2040:  3ffefb00 3fff5404 00000072 4020d678  
3fff2050:  3fff10fc 0000052c 0000052c 4010020c  
3fff2060:  00000000 3fff20c0 3fff2090 4010068c  
3fff2070:  3ffe84f9 00000000 3fff20c0 40214dd8  
3fff2080:  3fff10fc 000003fc 000003fc 4010020c  
3fff2090:  3ffe850f 3ffefb38 3fff20c0 4010068c  
3fff20a0:  3ffe84f9 000003ff 3ffefb2c 40214dd8  
3fff20b0:  3ffe850f 3fff0b57 3fff4f24 40208fb8  
3fff20c0:  00000000 00000000 00000000 00000000  
3fff20d0:  00000000 00000000 000003fc 4010020c  
3fff20e0:  00000001 00000001 3fff2110 4020f2cc  
3fff20f0:  00000001 00000001 3fff4ee4 4020f2c2  
3fff2100:  3fff4ee4 3ffefb78 3fff4ee4 4020f2fe  
3fff2110:  00000000 00000000 00000000 40214fe4  
3fff2120:  3fff4ee4 3ffefb78 3ffefb38 4020f38d  
3fff2130:  3fff46cc 0000000f 0000000d 4020d5cc  
3fff2140:  3ffefb78 3fffdad0 3fff11f0 00000001  
3fff2150:  00000001 4020e164 0000000a 3fff11f0  
3fff2160:  00000000 00000000 3ffefb38 3fff11e0  
3fff2170:  00000001 3ffefb5c 3ffefb38 4020f867  
3fff2180:  3fffdad0 00000000 3fff0428 40213149  
3fff2190:  3fff2b8c 4020ce38 3ffefab4 40208710  
3fff21a0:  3fffdad0 00000000 3ffefab4 4020a88a  
3fff21b0:  3ffe9784 00000000 3fff1124 4021441d  
3fff21c0:  3ffe8470 3fff3968 3fff1124 40214518  
3fff21d0:  40201236 00000000 3fff1124 3fff11e0  
3fff21e0:  3fffdad0 00000000 3ffefab4 40207033  
3fff21f0:  3fffdad0 00000000 3fff11d9 402158b0  
3fff2200:  feefeffe feefeffe 3fff11f0 40100718  
stack

 ets Jan  8 2013,rst cause:2, boot mode:(3,2)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld

**Comment by kerikun11** [comment]
@lucky62

Hello, 
Thank you for trying to use IR-Station.

According to the serial log, the Arguments must include "hostname", "ssid", "password", and "stealth" but the log doesn't include them.  Are the SSID and password in the serial log the same ones as you entered in the browser?

**Comment by lucky62** [comment]
Thanks for the response.
Serial log contains all required arguments:
Hostname: ir
SSID: myssid
Password: mypwd
Stealth: false

 After few erase/flash/fs-flash cycles the problem disappeared. So now everything is working.
I cannot reproduce the problem. Closing the issue.
