### ISSUE TITLE
Wont load main page, even for setup

### ISSUE THREAD

**Issue by Viniciusvalenca** [kerikun11/IR-station#8]
First thanks for the developer for this great work. Even without used it i already know how great this project is.
Well, my problem is, i have uploaded the latest code to my ESP chip, and all came good.
Coneccted to "IR-Station" wifi  but when i tried to open page for configure the problem appear. Wont worked! Its appear that the ESP stays on some loop. On serial console print this:

"New Request
URI: /
Method: GET
Arguments count: 0
End

New Request
URI: /favicon.ico
Method: GET
Arguments count: 0
End

New Request
URI: /
Method: GET
Arguments count: 0
End

New Request
URI: /favicon.ico
Method: GET
Arguments count: 0
End

New Request
URI: /
Method: GET
Arguments count: 0
End

New Request
URI: /
Method: GET
Arguments count: 0
End
"

If i wont stop or close the browser it stay on this loop.

Any one can help me? or give me some hint?

Very Thanks!

**Comment by kerikun11** [comment]
@Viniciusvalenca 

Did you upload HTML files to ESP's SPIFFS?
Sometimes it failes so please try again.
See https://github.com/esp8266/Arduino/blob/master/doc/filesystem.rst#uploading-files-to-file-system

**Comment by Viniciusvalenca** [comment]
Thanks! this was the problem.... my bad!
