### ISSUE TITLE
v1.5.1でStation Modeの初回wifi接続ができない

### ISSUE THREAD

**Issue by jp7fkf** [kerikun11/IR-station#9]
v1.4.0では接続ができるが，v1.5.1では接続ができないWifiがあるようです．
v1.4.0でもv1.5.1でも双方で接続できるWifiもあります．
環境によるものなのかもしれませんが，v1.4.0だときちんとできています．
原因が突き止められていません．すみません．

追記
バージョンにより接続できたりできなかったりというわけではないようでした．
場合によってまちまちで，再現性がありませんでした．すみません．

**Comment by jp7fkf** [comment]
なぜか起動後やwifi接続途中でEnd Receiving やnoise とprintされます．
ir recodeモードではないのに，です．
しばらく起動してるとexception になることもありました．
回路は全く同一ではないのですが，LEDをアノードコモンにしたりした程度なので，おそらく影響はないと思ってはいるのですが...．hmm...．

=====
New Request
URI: /mode/station
Method: GET
Arguments count: 4
  1073696012 = 1073688444
  1073696012 = 1073688444
  1073696012 = 1073688444
  1073696012 = 1073688444
Hostname: ir
SSID: xxxxxxxxx
Password: xxxxxxxxx
Stealth: false

New Request
URI: /wifi/confirm
Method: GET
Arguments count: 0
Not connected yet.
End
End Receiving
noise

New Request
URI: /wifi/confirm
Method: GET
Arguments count: 0
Not connected yet.
End
...


======
Hello, I'm ESP-WROOM-02
File Size: 215
Restore successful: /station.json
data: {"version":"v1.5.1","mode":0,"hostname":"ir","is_stealth_ssid":false,"ssid":"","password":"","is_static_ip":false,"local_ip":0,"subnetmask":0,"gateway":0,"next_id":1,"signals":[],"next_schedule_id":1,"schedules":[]}
Restored IR-Station Settings
OTA is Ready
Boot Mode: Setup
Configuring Access Point...
AP SSID : IR-Station
AP Password : IR-Station
AP IP address: 192.168.4.1
mDNS: http://ir.local
Starting Capital Portal...
Starting HTTP Updater...
Starting HTTP Server...
Starting SSDP...
Setup Completed
End Receiving
noise
End Receiving
noise

**Comment by jp7fkf** [comment]
issue #6 と似たようなことが起きているような気もします．
Arduino version:  1.8.5
board package: esp8266 2.4.0
SPIFFS，time等ライブラリは最新を使っています．

書き込み条件は下記の通りでよいでしょうか．

<img width="346" alt="screen shot 2018-02-28 at 18 08 56" src="https://user-images.githubusercontent.com/3335952/36779185-8645612e-1cb2-11e8-961d-7c6b0d598858.png">

v1.5.1のread meには
### Arduino Board Settings
| item | select |
| :---- | :---------------------- |
| Board | ESPino (ESP-12 Module) |
| Flash Mode | QIO |
| CPU Frequency | 80MHz |
| Flash Size | 4M\(3M SPIFFS\) |
| Reset Method | ck |
| Upload Speed | 115200 |

と書いてありますが，
masterブランチのhow to makeには

|item | select|
-- | --
Board | ESPino (ESP-12 Module)
Flash Mode | QIO
CPU Frequency | 160MHz
Flash Size | 4M(1M SPIFFS)
Reset Method | ck
Upload Speed | 115200

と書いてあるので気になっています．
最新のpackage にはFlash Modeを選択するところが無いようですが，あっていますでしょうか．
お教えいただければ幸いです．

**Comment by kerikun11** [comment]
@JP7FKF 

> なぜか起動後やwifi接続途中でEnd Receiving やnoise とprintされます．

については，周りに赤外線が飛んでいることが原因の可能性があります．
PWM調光のLED照明の場合などに起きることがありました．

`Flash Mode`はFlashの読み書きのスピードにかかわるものなので，動作には関係ないと思われます．
なので，添付画像の設定どおりで問題ないはずです．

**Comment by kerikun11** [comment]
`Flash Mode`はFlashの読み書きのスピードにかかわるものなので，動作には関係ないと思われます．
